# fly.toml app configuration file generated for tomhendra on 2024-09-01T18:21:01+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tomhendra'
primary_region = 'mad'

[build]

[http_service]
internal_port = 80
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
size = 'shared-cpu-1x'
memory_mb = 256
